target 'NeedlIOS' do
    source 'https://github.com/CocoaPods/Specs.git'
    pod 'Mixpanel'
    pod 'React', :subspecs => ['Core', 'RCTImage', 'RCTLinkingIOS', 'RCTNetwork', 'RCTText', 'RCTWebSocket'], :path => '../node_modules/react-native'
    pod 'react-native-fbsdkcore', :path => '../node_modules/react-native-fbsdk/iOS/core'
    pod 'react-native-fbsdklogin', :path => '../node_modules/react-native-fbsdk/iOS/login'
    pod 'react-native-fbsdkshare', :path => '../node_modules/react-native-fbsdk/iOS/share'
end